services:
  typescript-app:
    build:
      context: .
    container_name: typescript-app
    restart: unless-stopped
    init: true
    ports:
      - "4173:4173" # Expose Vite preview port
    # env_file: ./.env  # Uncomment if .env file exists
    # No external dependencies detected (database, cache, etc.)
    # If you add a database or other service, add it here and set up depends_on
    # volumes:  # No persistent volumes needed for this app
    #   - ./some-local-dir:/app/some-dir
    # networks:  # Uncomment if you add more services that need to communicate
    #   - appnet

# networks:
#   appnet:
#     driver: bridge
